services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  dbmanager:
    build: ./dbmanager
    environment:
      - FORCE_RECREATE=1
      - KEEP_ALIVE=0
      - OLLAMA_MODEL=qwen2.5:7b
    volumes:
      - db_data:/data
      - ./ml-latest-small:/app/ml-latest-small:ro
    depends_on:
      - ollama
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - db_data:/data:ro
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=qwen2.5:7b
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_PROJECT=MovieChatbot
      - LANGSMITH_API_KEY=REDACTED
    ports:
      - "8000:8000"
    depends_on:
      - dbmanager
      - ollama

  webapp:
    build: ./webapp
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/query/
    depends_on:
      - backend
    volumes:
      - ./webapp:/app

volumes:
  db_data:
    driver: local

