services:

  dbmanager:
    build: ./dbmanager
    environment:
      - FORCE_RECREATE=1
      - KEEP_ALIVE=1
    # restart: unless-stopped
    volumes:
      - db_data:/data
      - ./ml-latest-small:/app/ml-latest-small:ro
 

  backend:
    build: ./backend
    volumes:
      - db_data:/data:ro
    environment:
      - GROQ_MODEL=openai/gpt-oss-120b
      - GROQ_API_KEY=REDACTED
      - LANGSMITH_ENDPOINT=https://api.smith.langchain.com
      - LANGSMITH_PROJECT=MovieChatbot
      - LANGSMITH_API_KEY=REDACTED
    ports:
      - "8000:8000"
    depends_on:
      - dbmanager

  webapp:
    build: ./webapp
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/query/
    depends_on:
      - backend
    volumes:
      - ./webapp:/app

volumes:
  db_data:
    driver: local

